In [30]:
import pandas as pd
import numpy as np
from pandas import DataFrame
from sklearn.preprocessing import minmax_scale

In [31]:
# Read data
data = pd.read_csv('RawData/FirmData.csv')
data["Year"] = pd.to_datetime(data["Date"], dayfirst=True).dt.year
data.head(5)

,RIC,Date,Total Equity,Company Market Cap,Revenue,Full-Time Employees,"Cash Dividend Paid, Common, Discrete",Year
0,BAYGn.DE,31/12/1995,8488.469784,NaN,22200.29864,148248,382.4463271,1995
1,BAYGn.DE,31/12/1996,9109.178272,23034.05554,22793.39736,142900,463.7417362,1996
2,BAYGn.DE,31/12/1997,10532.10391,24409.89006,24852.88154,142200,543.5032697,1997
3,BAYGn.DE,31/12/1998,12008.20391,26146.11494,28123.61646,144600,634.0019327,1998
4,BAYGn.DE,31/12/1999,12566.53478,34399.10820,23351.72822,145100,364.0398194,1999

In [32]:
# Convert dataframe to correct format
df_Sales = data.pivot(index="RIC", columns="Year", values="Revenue")
for i in df_Sales.columns:
    df_Sales[i] = pd.to_numeric(df_Sales[i], errors='coerce')
df_Sales.head(5)

Year,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
RIC,,,,,,,,,,,,,,,,,,,,,
05P.D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0955.HK^D12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,115.304,115.304,115.304,115.304,115.304,115.304,115.304,115.304,115.304,115.304
0FIBG.DE^F10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.808,0.508,...,-0.616,-0.616,-0.616,-0.616,-0.616,-0.616,-0.616,-0.616,-0.616,-0.616
0RN6.L^G19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,282.436,294.436,290.658,290.658,290.658,322.554,322.554,322.554,322.554,322.554
123F.DE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
for year in df_Sales.columns:
    df_Sales[year] = minmax_scale(df_Sales[year])
df_Sales

Year,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
RIC,,,,,,,,,,,,,,,,,,,,,
05P.D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0955.HK^D12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000779,0.000602,0.000588,0.000573,0.000543,0.000537,0.000505,0.000491,0.000459,0.000535
0FIBG.DE^F10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000038,0.000017,...,0.000025,0.000000,0.000000,0.000000,0.000000,0.000003,0.000000,0.000000,0.000000,0.000015
0RN6.L^G19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.001866,0.001531,0.001478,0.001439,0.001366,0.001491,0.001408,0.001370,0.001279,0.001465
123F.DE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZO1G.H,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000161,...,0.001701,0.001660,0.002069,0.002686,0.003338,0.004188,0.004841,0.005691,0.006034,0.008101
ZOOG.BE,NaN,NaN,NaN,NaN,0.000061,0.000151,0.000149,0.000161,0.000090,0.000080,...,0.000134,0.000088,0.000087,0.000092,0.000090,0.000107,0.000110,0.000109,0.000112,0.000095
ZPFGn.MU,NaN,NaN,NaN,NaN,NaN,0.000994,0.001292,0.001395,0.001544,0.001490,...,0.000393,0.000300,0.000270,0.000299,0.000311,0.000328,0.000345,0.000380,0.000418,0.000389
ZUKG.SG^E15,NaN,NaN,NaN,NaN,NaN,0.000109,0.000105,0.000112,0.000034,0.000015,...,0.000029,0.000003,0.000003,0.000003,0.000003,0.000006,0.000003,0.000003,0.000002,0.000018
ZZSG.DE^L07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
# Check if all columns have data type float64 e.g. only contain numbers
df_Sales.dtypes

Year
1995    float64
1996    float64
1997    float64
1998    float64
1999    float64
2000    float64
2001    float64
2002    float64
2003    float64
2004    float64
2005    float64
2006    float64
2007    float64
2008    float64
2009    float64
2010    float64
2011    float64
2012    float64
2013    float64
2014    float64
2015    float64
2016    float64
2017    float64
2018    float64
2019    float64
2020    float64
2021    float64
dtype: object

In [35]:
# Write dataframe
df_Sales.to_pickle("UsableData/Sales.pkl")