In [12]:
import pandas as pd
import numpy as np
from pandas import DataFrame

In [13]:
# Read returns to calculate the variance of the returns and create empty dataframe
df_Returns = pd.read_pickle("UsableData/Returns.pkl").T
df_Variance = DataFrame()

In [14]:
# Calculate variance of returns for each year and stock
years = df_Returns.index.year.unique()
for year in years:
    returns = df_Returns[(df_Returns.index >= f"{year}-01-01") & (df_Returns.index <= f"{year}-12-31")]
    for ric in returns.columns:
        df_Variance.at[ric, year] = np.var(returns[ric])
df_Variance.head(5)

,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
BAYGn.DE,27.277955,10.640167,33.616449,65.208538,84.213922,50.606431,101.453746,75.299604,157.435071,252.742107,...,23.782625,10.166175,25.168869,48.146520,53.435813,18.781626,42.751437,94.638878,171.117206,21.802115
DTEGn.DE,NaN,NaN,3.794764,76.764409,83.917071,240.927008,153.665688,199.345848,301.718945,53.413115,...,21.293172,25.647276,32.375216,38.451525,17.785673,18.031197,24.467956,9.998793,88.196160,31.506536
MBGn.DE,476.653075,36.298345,27.112524,80.901484,110.622961,103.749032,63.244981,209.605330,96.598755,79.499738,...,92.895078,46.785289,23.149857,97.272893,76.154301,22.154361,22.577492,75.316471,195.066543,44.906480
ALVG.DE,26.108533,26.787488,12.544280,109.110125,81.846124,70.860344,49.283757,44.183541,222.090548,539.614641,...,35.948301,26.457708,16.946108,32.954334,40.185225,8.086683,26.091592,16.606845,150.003505,26.136106
SIEGn.DE,35.540292,9.241408,14.552579,88.154216,164.178416,98.670381,189.744805,266.289133,282.026996,85.539963,...,17.304772,25.556056,9.829735,56.518934,27.104807,26.144146,27.236408,40.006989,92.366133,19.835380

In [15]:
# Save dataframe
df_Variance.to_pickle("UsableData/Variance.pkl")