In [1]:
import pandas as pd
import numpy as np
data = pd.read_csv('MarketCap.csv')
data

,RIC,31/01/1994,28/02/1994,31/03/1994,30/04/1994,31/05/1994,30/06/1994,31/07/1994,31/08/1994,30/09/1994,...,31/03/2021,30/04/2021,31/05/2021,30/06/2021,31/07/2021,31/08/2021,30/09/2021,31/10/2021,30/11/2021,31/12/2021
0,BAYGn.DE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,53011.60346,52874.06409,50575.19174,50309.93724,49406.10708,46316.38335,46178.84397,47814.58007,43737.52013,46276.10860
1,DTEGn.DE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,81754.24409,76183.33754,80916.22738,84811.10051,83354.09418,85744.34640,86744.43374,80172.28131,77728.91659,81279.27511
2,MBGn.DE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,81318.34435,79221.46295,81489.51834,80558.75976,80537.36301,76407.79046,82077.92893,91727.86271,88796.50810,72310.31304
3,ALVG.DE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,89488.22343,89220.23290,88828.55443,86705.24482,86581.55688,82038.08661,80331.19306,82932.76270,78603.63308,84816.27733
4,SIEGn.DE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,119000.00000,117997.00000,112744.00000,113577.00000,111843.00000,119714.00000,120632.00000,119238.00000,120088.00000,129778.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1715,TCP.SG^C16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1716,DWH.VI^C20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,243.54000,243.54000,243.54000,243.54000,243.54000,243.54000,243.54000,243.54000,243.54000,243.54000
1717,SIGN.VI^H21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.66000,715.00000,726.00000,0.88000,825.00000,825.00000,825.00000,825.00000,825.00000,825.00000
1718,DE016013382=ISMA^D10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1719,IGY.BN^F20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
nan_count = data["RIC"].isna().sum()

# Print the result
print("Number of NaN values in RIC column:", nan_count)

Number of NaN values in RIC column: 0